#!/bin/bash
# Setup Echo Cancellation for PipeWire
# This script creates the proper PipeWire configuration for echo cancellation

set -e

echo "========================================="
echo "  PipeWire Echo Cancellation Setup"
echo "========================================="
echo ""

# Step 1: List available audio devices
echo "📋 Available Audio Devices:"
echo ""
echo "Sources (Microphones):"
pactl list short sources
echo ""
echo "Sinks (Speakers):"
pactl list short sinks
echo ""

# Step 2: Prompt for device selection
echo "========================================="
echo "  Device Selection"
echo "========================================="
echo ""
log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

log_success() {
    echo "[SUCCESS] $1"
}

echo "You need to specify your microphone and speaker devices."
echo "Look at the list above and find your devices."
echo ""
echo "Example device names:"
echo "  Microphone: alsa_input.usb-Audio_Array_AM-C28_Device_2023-08-22-0001-00.iec958-stereo"
echo "  Speaker:    alsa_output.usb-Generic_GHW-123P_20210726905926-00.iec958-stereo"
echo ""

read -p "Enter your MICROPHONE device name (source_master): " MIC_DEVICE
if [ -z "$MIC_DEVICE" ]; then
    log_error "Microphone device cannot be empty"
    exit 1
fi

read -p "Enter your SPEAKER device name (sink_master): " SPEAKER_DEVICE
if [ -z "$SPEAKER_DEVICE" ]; then
    log_error "Speaker device cannot be empty"
    exit 1
fi

echo ""
log_info "Configuration:"
echo "  Microphone: $MIC_DEVICE"
echo "  Speaker:    $SPEAKER_DEVICE"
echo ""

read -p "Is this correct? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    log_info "Setup cancelled"
    exit 0
fi

# Step 3: Create config directory
log_info "Creating PipeWire configuration directory..."
mkdir -p ~/.config/pipewire/pipewire-pulse.conf.d

# Step 4: Create echo cancellation config
CONFIG_FILE="$HOME/.config/pipewire/pipewire-pulse.conf.d/20-echo-cancel.conf"

log_info "Creating echo cancellation configuration..."
cat > "$CONFIG_FILE" <<EOF
# PipeWire Echo Cancellation Configuration
# Generated by setup-echo-cancel.sh

pulse.cmd = [
    { cmd = "load-module" args = "module-echo-cancel source_master=$MIC_DEVICE sink_master=$SPEAKER_DEVICE source_name=echo_cancel.mic sink_name=echo_cancel.speaker use_master_format=1 aec_method=webrtc aec_args=\\"analog_gain_control=0\\"" }
]
EOF

log_success "Configuration created at: $CONFIG_FILE"

# Step 5: Restart PipeWire services
log_info "Restarting PipeWire services to apply configuration..."
systemctl --user restart wireplumber
systemctl --user restart pipewire pipewire-pulse

# Step 6: Wait for services to initialize
log_info "Waiting for services to initialize..."
sleep 3

# Step 7: Verify echo cancellation devices
echo ""
log_info "Verifying echo cancellation setup..."

if pactl list short sources | grep -q "echo_cancel.mic"; then
    log_success "✓ Echo cancellation microphone (echo_cancel.mic) created"
else
    log_error "✗ Echo cancellation microphone not found"
    echo "Check logs: journalctl --user -u pipewire-pulse -n 50"
    exit 1
fi

if pactl list short sinks | grep -q "echo_cancel.speaker"; then
    log_success "✓ Echo cancellation speaker (echo_cancel.speaker) created"
else
    log_error "✗ Echo cancellation speaker not found"
    echo "Check logs: journalctl --user -u pipewire-pulse -n 50"
    exit 1
fi

echo ""
echo "========================================="
log_success "Echo Cancellation Setup Complete!"
echo "========================================="
echo ""
echo "Virtual devices created:"
echo "  - echo_cancel.mic (microphone with AEC)"
echo "  - echo_cancel.speaker (speaker with AEC)"
echo ""
echo "Update your .env file to use these devices:"
echo "  MIC_DEVICE=echo_cancel.mic"
echo "  SPEAKER_DEVICE=echo_cancel.speaker"
echo ""
echo "Test echo cancellation:"
echo "  1. Play audio through echo_cancel.speaker"
echo "  2. Record from echo_cancel.mic"
echo "  3. The recorded audio should NOT contain the played audio"
echo ""
echo "To remove echo cancellation:"
echo "  rm ~/.config/pipewire/pipewire-pulse.conf.d/20-echo-cancel.conf"
echo "  systemctl --user restart pipewire pipewire-pulse"
echo ""

