#!/bin/bash
# =============================================================================
# ALSA Loopback Setup for Speaker Monitoring
# =============================================================================
# This script sets up an ALSA loopback device that allows monitoring speaker
# output without changing how audio playback works.
#
# How it works:
# 1. Loads snd-aloop kernel module (creates virtual loopback device)
# 2. Creates ALSA config that duplicates output to both ReSpeaker AND loopback
# 3. SpeakerMonitor can then read from the loopback to detect agent speech
#
# Usage:
#   sudo ./install-loopback.sh
#
# To uninstall:
#   sudo ./uninstall-loopback.sh
# =============================================================================

set -e

echo "=========================================="
echo "📊 ALSA Loopback Setup for Speaker Monitor"
echo "=========================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Please run as root (sudo ./install-loopback.sh)"
    exit 1
fi

# Get the actual user (not root)
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

echo ""
echo "1️⃣  Loading snd-aloop kernel module..."

# Load the loopback module
if ! lsmod | grep -q snd_aloop; then
    modprobe snd-aloop
    echo "   ✓ snd-aloop module loaded"
else
    echo "   ✓ snd-aloop module already loaded"
fi

# Make it persistent across reboots
if ! grep -q "snd-aloop" /etc/modules-load.d/*.conf 2>/dev/null; then
    echo "snd-aloop" > /etc/modules-load.d/snd-aloop.conf
    echo "   ✓ Added to /etc/modules-load.d/snd-aloop.conf (persistent)"
else
    echo "   ✓ Already in modules-load.d (persistent)"
fi

echo ""
echo "2️⃣  Creating ALSA configuration..."

# Find ReSpeaker device card number
RESPEAKER_CARD=""
for card in /proc/asound/card*/id; do
    if [ -f "$card" ]; then
        card_id=$(cat "$card")
        card_num=$(echo "$card" | grep -o 'card[0-9]*' | grep -o '[0-9]*')
        if echo "$card_id" | grep -iq -E "(respeaker|arrayuac|uac1)"; then
            RESPEAKER_CARD="$card_num"
            echo "   Found ReSpeaker at card $RESPEAKER_CARD ($card_id)"
            break
        fi
    fi
done

if [ -z "$RESPEAKER_CARD" ]; then
    echo "   ⚠️  ReSpeaker not found, using 'default' for playback"
    PLAYBACK_DEVICE="default"
else
    PLAYBACK_DEVICE="hw:$RESPEAKER_CARD"
fi

# Find Loopback device card number
LOOPBACK_CARD=""
for card in /proc/asound/card*/id; do
    if [ -f "$card" ]; then
        card_id=$(cat "$card")
        card_num=$(echo "$card" | grep -o 'card[0-9]*' | grep -o '[0-9]*')
        if echo "$card_id" | grep -iq "loopback"; then
            LOOPBACK_CARD="$card_num"
            echo "   Found Loopback at card $LOOPBACK_CARD"
            break
        fi
    fi
done

if [ -z "$LOOPBACK_CARD" ]; then
    echo "   ❌ Loopback device not found. Is snd-aloop loaded?"
    exit 1
fi

# Create ALSA config file
ASOUND_CONF="/etc/asound.conf"

cat > "$ASOUND_CONF" << EOF
# =============================================================================
# ALSA Configuration for Speaker Monitoring
# Generated by install-loopback.sh
# =============================================================================
# This config creates a virtual output device that sends audio to both:
# 1. The real speaker (ReSpeaker)
# 2. A loopback device (for monitoring)
#
# The SpeakerMonitor reads from the loopback to detect agent speech.
# =============================================================================

# -----------------------------------------------------------------------------
# Loopback Playback (where we write the duplicate audio)
# -----------------------------------------------------------------------------
pcm.loopback_out {
    type plug
    slave.pcm "hw:${LOOPBACK_CARD},0,0"
}

# -----------------------------------------------------------------------------
# Loopback Capture (where SpeakerMonitor reads from)
# This is the "speaker_monitor" device that captures what's being played
# -----------------------------------------------------------------------------
pcm.speaker_monitor {
    type plug
    slave {
        pcm "hw:${LOOPBACK_CARD},1,0"
        rate 16000
        channels 1
    }
}

# -----------------------------------------------------------------------------
# Multi-output device: sends audio to both ReSpeaker AND loopback
# This is used as the playback device when monitoring is enabled
# -----------------------------------------------------------------------------
pcm.speaker_with_monitor {
    type plug
    slave.pcm {
        type multi
        slaves {
            a { pcm "${PLAYBACK_DEVICE}" channels 2 }
            b { pcm "hw:${LOOPBACK_CARD},0,0" channels 2 }
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable {
        0.0 1
        0.2 1
        1.1 1
        1.3 1
    }
}

# -----------------------------------------------------------------------------
# Default output - routes to both speaker AND loopback for monitoring
# This enables speaker monitoring without requiring app-specific config
# -----------------------------------------------------------------------------
pcm.!default {
    type plug
    slave.pcm "speaker_with_monitor"
}

ctl.!default {
    type hw
    card ${RESPEAKER_CARD:-0}
}
EOF

echo "   ✓ Created $ASOUND_CONF"

echo ""
echo "3️⃣  Testing configuration..."

# Test that the loopback device is accessible
if aplay -l 2>/dev/null | grep -q "Loopback"; then
    echo "   ✓ Loopback device accessible"
else
    echo "   ⚠️  Loopback device not showing in aplay -l"
fi

# Test that speaker_monitor is readable
if arecord -L 2>/dev/null | grep -q "speaker_monitor"; then
    echo "   ✓ speaker_monitor device configured"
else
    echo "   ⚠️  speaker_monitor not in arecord -L (may need alsactl restore)"
fi

echo ""
echo "=========================================="
echo "✅ ALSA Loopback Setup Complete!"
echo "=========================================="
echo ""
echo "To enable speaker monitoring in the client:"
echo "  export SPEAKER_MONITOR_MODE=loopback"
echo ""
echo "The following ALSA devices are now available:"
echo "  • speaker_monitor  - Read from this to capture speaker output"
echo "  • loopback_out     - Loopback playback (internal)"
echo "  • speaker_with_monitor - Multi-output (speaker + loopback)"
echo ""
echo "Note: A reboot may be required for all changes to take effect."
echo ""

